import * as colors from './_colors';
import * as darkColors from './_dark-colors';

// This is base theme props used in every theme.
const commonThemeConfig = {
  props: {
    MuiButtonBase: {
      disableRipple: true,
    },
    MuiButton: {
      disableElevation: true,
    },
  },
  shape: {
    borderRadius: '2px',
  },
  palette: {
    error: {
      main: colors.formError,
    },
  },
  breakpoints: {
    values: {
      lg: 1216, md: 960, sm: 600, xl: 1920, xs: 0,
    },
  },
  colors: {
    skeletonColor1: colors.skeletonColor1,
    footerColor: colors.footerColor,
    lightSilver: colors.lightSilver,
    veryLightGray: colors.veryLightGray,
    borderGray: colors.borderGray,
    lightGray: colors.lightGray,
    mediumLightGray: colors.mediumLightGray,
    mediumGray: colors.mediumGray,
    mediumDarkGray: colors.mediumDarkGray,
    darkGray: colors.darkGray,
    veryDarkGray: colors.veryDarkGray,
    black: colors.black,
    white: colors.white,
    formInfo: colors.formInfo,
    veryLightLimeGreen: colors.veryLightLimeGreen,
    lightLimeGreen: colors.lightLimeGreen,
    lightVividPink: colors.lightVividPink,
    limeGreen: colors.limeGreen,
    darkLimeGreen: colors.darkLimeGreen,
    veryDarkLimeGreen: colors.veryDarkLimeGreen,
    desaturatedDarkLimeGreen: colors.desaturatedDarkLimeGreen,
    funGreen: colors.funGreen,
    lightGreen: colors.lightGreen,
    veryLightGreen: colors.veryLightGreen,
    greenBorder: colors.greenBorder,
    pinkBorder: colors.pinkBorder,
    lightCyanBorder: colors.lightCyanBorder,
    veryLightBlue: colors.veryLightBlue,
    lightBlue: colors.lightBlue,
    softBlue: colors.softBlue,
    brightBlue: colors.brightBlue,
    strongBlue: colors.strongBlue,
    facebook: colors.facebook,
    twitter: colors.twitter,
    linkedin: colors.linkedin,
    darkCyan: colors.darkCyan,
    textWhite: colors.textWhite,
    textBlack: colors.textBlack,
    vividPink: colors.vividPink,
    formLightGreen: colors.formLightGreen,
    formSuccess: colors.formSuccess,
    formError: colors.formError,
    gold: colors.gold,
    veryLightRed: darkColors.veryLightRed,
    lightRed: colors.lightRed,
    red: colors.red,
    orange: colors.orange,
    orange2: colors.orange2,
    oldOrange: colors.oldOrange,
    deepPink: colors.deepPink,
    darkViolet: colors.darkViolet,
    deepSkyBlue: colors.deepSkyBlue,
    veryDarkViolet: colors.veryDarkViolet,
    lightPurple: colors.lightPurple,
  },
  darkColors: {
    skeletonColor1: darkColors.skeletonColor1,
    footerColor: darkColors.footerColor,
    lightSilver: darkColors.lightSilver,
    veryLightGray: darkColors.veryLightGray,
    borderGray: colors.borderGray,
    lightGray: darkColors.lightGray,
    mediumLightGray: darkColors.mediumLightGray,
    mediumGray: darkColors.mediumGray,
    mediumDarkGray: darkColors.mediumDarkGray,
    darkGray: darkColors.darkGray,
    veryDarkGray: darkColors.veryDarkGray,
    black: darkColors.black,
    white: darkColors.white,
    formInfo: darkColors.formInfo,
    veryLightLimeGreen: darkColors.veryLightLimeGreen,
    lightLimeGreen: darkColors.lightLimeGreen,
    lightVividPink: darkColors.lightVividPink,
    limeGreen: darkColors.limeGreen,
    darkLimeGreen: darkColors.darkLimeGreen,
    veryDarkLimeGreen: darkColors.veryDarkLimeGreen,
    desaturatedDarkLimeGreen: darkColors.desaturatedDarkLimeGreen,
    funGreen: darkColors.funGreen,
    lightGreen: darkColors.lightGreen,
    veryLightGreen: darkColors.veryLightGreen,
    greenBorder: darkColors.greenBorder,
    pinkBorder: darkColors.pinkBorder,
    lightCyanBorder: darkColors.lightCyanBorder,
    veryLightBlue: darkColors.veryLightBlue,
    lightBlue: darkColors.lightBlue,
    softBlue: darkColors.softBlue,
    brightBlue: darkColors.brightBlue,
    strongBlue: darkColors.strongBlue,
    facebook: darkColors.facebook,
    twitter: darkColors.twitter,
    linkedin: darkColors.linkedin,
    darkCyan: darkColors.darkCyan,
    textWhite: darkColors.textWhite,
    textBlack: darkColors.textBlack,
    vividPink: darkColors.vividPink,
    formLightGreen: darkColors.formLightGreen,
    formSuccess: darkColors.formSuccess,
    formError: darkColors.formError,
    gold: darkColors.gold,
    veryLightRed: darkColors.veryLightRed,
    lightRed: darkColors.lightRed,
    red: darkColors.red,
    orange: darkColors.orange,
    orange2: darkColors.orange2,
    oldOrange: colors.oldOrange,
    deepPink: darkColors.deepPink,
    darkViolet: darkColors.darkViolet,
    deepSkyBlue: darkColors.deepSkyBlue,
    veryDarkViolet: darkColors.veryDarkViolet,
    lightPurple: colors.lightPurple,
  },
  typography: {
    h1: {
      fontWeight: 'bold',
      fontSize: '80px',
    },
    h2: {
      fontWeight: 'bold',
      fontSize: '60px',
    },
    h3: {
      fontWeight: 'bold',
      fontSize: '30px',
    },
    h4: {
      fontWeight: 'bold',
      fontSize: '24px',
    },
    h5: {
      fontWeight: 'bold',
      fontSize: '22px',
    },
    body1: {
      fontWeight: 'normal',
      fontSize: '16px',
    },
    caption: {
      fontWeight: 'normal',
      fontSize: '18px',
    },
  },
};

export default commonThemeConfig;
