/** The properties of MuiTheme interface have been taken by manually logging it's values (in _app.jsx)
 * it's values are imported from "GreenTheme" from salalem.dist .
 * Ideally we would want to export an interface from salalem.dist so that the values of the MuiTheme
 * interface would always be up to date.
 */

import { Theme } from '@material-ui/core/styles';

/** 
 * @summary The Salalem theme that includes extra properties used in the makeStyles "theme" callback argument
 * @extends Theme
 */
export interface MuiTheme extends Theme {
    colors: {
        black: "#000000"
        borderGray: "#ECECEC"
        brightBlue: "#4CBABB"
        darkCyan: "#21ABAB"
        darkGray: "#ADADAD"
        darkLimeGreen: "#70BF90"
        darkViolet: "#AF8ACA"
        deepPink: "#EA607C"
        deepSkyBlue: "#70BFE6"
        desaturatedDarkLimeGreen: "#70A665"
        facebook: "#3B5998"
        footerColor: "#DDDDDD"
        formError: "#E60278"
        formInfo: "#21ABAB"
        formLightGreen: "#86D1A5"
        formSuccess: "#6FCF97"
        funGreen: "#40C173"
        gold: "#EA9721"
        greenBorder: "#28A564"
        lightBlue: "#A3EAEA"
        lightCyanBorder: "#21ABAB"
        lightGray: "#EEEEEE"
        lightGreen: "#9ED155"
        lightLimeGreen: "#F3F9F2"
        lightPurple: "#AF8ACA"
        lightRed: "#F45671"
        lightSilver: "#E1E1E1"
        lightVividPink: "#F0D3E2"
        limeGreen: "#86D1A5"
        linkedin: "#007BB6"
        mediumDarkGray: "#DADADA"
        mediumGray: "#E0E0E0"
        mediumLightGray: "#E9E9E9"
        oldOrange: "#FFD06E"
        orange: "#FFD06E"
        orange2: "#FBD06D"
        pinkBorder: "#E60278"
        red: "#E81010"
        skeletonColor1: "#f7f7f7"
        softBlue: "#9EDCEF"
        strongBlue: "#70BFE6"
        textBlack: "#2C2C2C"
        textWhite: "#FFFFFF"
        twitter: "#2CA7E0"
        veryDarkGray: "#757575"
        veryDarkLimeGreen: "#476B56"
        veryDarkViolet: "#5C3A91"
        veryLightBlue: "#E2F2FA"
        veryLightGray: "#F5F5F5"
        veryLightGreen: "#DFEFE3"
        veryLightLimeGreen: "#F7F9F6"
        veryLightRed: "#FDE0E5"
        vividPink: "#E60278"
        white: "#FFFFFF"
    }
    darkColors: {
        black: "#FFFFFF"
        borderGray: "#ECECEC"
        brightBlue: "#4CBABB"
        darkCyan: "#21ABAB"
        darkGray: "#ADADAD"
        darkLimeGreen: "#99D0AE"
        darkViolet: "#AF8ACA"
        deepPink: "#F06292"
        deepSkyBlue: "#70BFE6"
        desaturatedDarkLimeGreen: "#70A665"
        facebook: "#3B5998"
        footerColor: "#121212"
        formError: "#492632"
        formInfo: "#203C3C"
        formLightGreen: "#86D1A5"
        formSuccess: "#344139"
        funGreen: "#219653"
        gold: "#EEB463"
        greenBorder: "#99D0AE"
        lightBlue: "#A3EAEA"
        lightCyanBorder: "#4CBABB"
        lightGray: "#393939"
        lightGreen: "#9ED155"
        lightLimeGreen: "#262E29"
        lightPurple: "#AF8ACA"
        lightRed: "#F45671"
        lightSilver: "#ADADAD"
        lightVividPink: "#492632"
        limeGreen: "#86D1A5"
        linkedin: "#007BB6"
        mediumDarkGray: "#393939"
        mediumGray: "#424242"
        mediumLightGray: "#424242"
        oldOrange: "#FFD06E"
        orange: "#FFD06E"
        orange2: "#FFAF4D"
        pinkBorder: "#F06292"
        red: "#E60278"
        skeletonColor1: "#424242"
        softBlue: "#9EDCEF"
        strongBlue: "#70BFE6"
        textBlack: "#C9C9C9"
        textWhite: "#2C2C2C"
        twitter: "#2CA7E0"
        veryDarkGray: "#E1E1E1"
        veryDarkLimeGreen: "#99D0AE26"
        veryDarkViolet: "#232323"
        veryLightBlue: "#E2F2FA"
        veryLightGray: "#121212"
        veryLightGreen: "#DFEFE3"
        veryLightLimeGreen: "#232323"
        veryLightRed: "#FDE0E5"
        vividPink: "#F06292"
        white: "#2E2E2E"
    }
    name: string,
}